// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBEULoXBPEgy4hKicAuOsENRQuyIPt2w',
    appId: '1:766247667208:web:87bbeef9fe4ab23049b3bd',
    messagingSenderId: '766247667208',
    projectId: 'speakbuddy-1da6d',
    authDomain: 'speakbuddy-1da6d.firebaseapp.com',
    storageBucket: 'speakbuddy-1da6d.firebasestorage.app',
    measurementId: 'G-WSEVWJD428',
    databaseURL: 'https://speakbuddy-1da6d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsqkoHDw7BrIa4A7X74H__hZ4ZUDYraI',
    appId: '1:766247667208:android:3c71aaa713efb8ba49b3bd',
    messagingSenderId: '766247667208',
    projectId: 'speakbuddy-1da6d',
    storageBucket: 'speakbuddy-1da6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq60vIVvDr7Stgm7PK5UMCSH_9Z5Jvk50',
    appId: '1:766247667208:ios:9c7ea0f9b31846eb49b3bd',
    messagingSenderId: '766247667208',
    projectId: 'speakbuddy-1da6d',
    storageBucket: 'speakbuddy-1da6d.firebasestorage.app',
    iosClientId: '766247667208-n9hj75g4okq1chr4s1kdejdmon06agqd.apps.googleusercontent.com',
    iosBundleId: 'com.speakbuddy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq60vIVvDr7Stgm7PK5UMCSH_9Z5Jvk50',
    appId: '1:766247667208:ios:9c7ea0f9b31846eb49b3bd',
    messagingSenderId: '766247667208',
    projectId: 'speakbuddy-1da6d',
    storageBucket: 'speakbuddy-1da6d.firebasestorage.app',
    iosClientId: '766247667208-n9hj75g4okq1chr4s1kdejdmon06agqd.apps.googleusercontent.com',
    iosBundleId: 'com.speakbuddy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIBEULoXBPEgy4hKicAuOsENRQuyIPt2w',
    appId: '1:766247667208:web:fd15343904c3b72249b3bd',
    messagingSenderId: '766247667208',
    projectId: 'speakbuddy-1da6d',
    authDomain: 'speakbuddy-1da6d.firebaseapp.com',
    storageBucket: 'speakbuddy-1da6d.firebasestorage.app',
    measurementId: 'G-NCXJVSYZCN',
  );
}
